### ISSUE TITLE
Incomprehensible error

### ISSUE THREAD

**Issue by Mika2273** [cnumr/GreenIT-Analysis-cli#17]
I get an error when analyzing the yaml file generated from the sitemap.
I attach the error log and the yaml file.
log
```
Analysing                [========================================] 100%     Remaining: 0.0s     Time: 12.5s
ERROR : 
 Error: Protocol error: Connection closed. Most likely the page has been closed.
    at Object.exports.assert (/home/mito/Test/GreenIT-Analysis/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26:15)
    at Page.close (/home/mito/Test/GreenIT-Analysis/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1198:21)
    at /home/mito/Test/GreenIT-Analysis/commands/analyse.js:68:49
    at Array.map (<anonymous>)
    at analyse_core (/home/mito/Test/GreenIT-Analysis/commands/analyse.js:68:33)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
yaml
```
- url: https://angleweb.fr/
- url: https://angleweb.fr/sites-internet/
- url: https://angleweb.fr/sites-internet/creation-site-internet/
- url: https://angleweb.fr/sites-internet/refonte-site-internet/
- url: https://angleweb.fr/conseil-formation/
- url: https://angleweb.fr/conseil-formation/audit-site-internet/
- url: https://angleweb.fr/conseil-formation/express-conseil-web/
- url: https://angleweb.fr/conseil-formation/assistance-a-maitrise-douvrage-web/
- url: https://angleweb.fr/references/
- url: https://angleweb.fr/blog/idees-recues-eco-conception-sites-web/
- url: https://angleweb.fr/blog/quels-outils-pour-evaluer-impact-environnemental-de-son-site-internet/
- url: https://angleweb.fr/blog/emails-tester-spam/
- url: https://angleweb.fr/blog/gvu-immo/
- url: https://angleweb.fr/blog/etude-empreinte-environnementale-numerique-mondial/
- url: https://angleweb.fr/blog/guide-ultime-cms-partie-1/
- url: https://angleweb.fr/blog/creation-site-internet-de-swap-annecy/
- url: https://angleweb.fr/blog/optimiser-ses-url-pour-un-seo-efficace/
- url: https://angleweb.fr/blog/nouveau-site-internet-mairie-saint-offenge/
- url: https://angleweb.fr/blog/ecommerce-parfums-et-montagnes/
- url: https://angleweb.fr/blog/nouveau-logo-saint-offenge/
- url: https://angleweb.fr/blog/hashtags-motdiese-choisir/
- url: https://angleweb.fr/blog/seo-crawler-url/
- url: https://angleweb.fr/blog/guide-http-vers-https/
- url: https://angleweb.fr/agence-web-responsable/
- url: https://angleweb.fr/agence-web-responsable/eco-conception-web/
- url: https://angleweb.fr/contact/
- url: https://angleweb.fr/plan-du-site/

```

**Comment by jpreisner** [comment]
Hi @Mika2273, sorry for my late response. Thank you for creating your issue. This actually needs a fix. I suggest that you close this issue because #27 already raises the problem and @Krakor92 did an analysis.
